[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmds = [
  'cd review-imdb && npm install'
]

[phases.build]
cmds = [
  'cd review-imdb && npm run build'
]

[start]
cmd = 'cd review-imdb && npm run start -- -p $PORT'
